# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    # Образ сервиса app, который в docker-compose.yaml. Помещён в local docker registry, поэтому указан адреc образа из registry.
    image: localhost:5000/app
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  #Nginx Service
  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
volumes:
  dbdata:
    driver: local
