# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
   #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
